import type { LocationId } from '../../game/types'
import type { WorldLocation } from './types'

export const WORLD_LOCATIONS: Record<LocationId, WorldLocation> = {
  home: {
    id: 'home',
    name: 'Tổ Ấm Chiikawa & Usagi',
    subtitle: 'Đếm Ngày Yêu · Lời Nhắn Ấm Áp',
    category: 'core',
    position: { x: 48, y: 48 },
    characterAnchor: { x: 48, y: 55 },
    img: './assets/buildings/home.png',
    icon: '🏠',
    color: '#ff8da1',
    glow: 'rgba(255, 141, 161, 0.5)',
    tag: 'TỔ ẤM',
    size: 110,
    transition: 'heart',
    ambienceId: 'ambient_home_chime',
    unlockLevel: 1,
    defaultLevel: 1
  },
  quests: {
    id: 'quests',
    name: 'Quảng Trường Kế Hoạch 10 Ngày',
    subtitle: 'Nhiệm Vụ Mỗi Ngày · Checklist Sẵn Sàng',
    category: 'core',
    position: { x: 68, y: 38 },
    characterAnchor: { x: 68, y: 45 },
    img: './assets/buildings/quests.png',
    icon: '📋',
    color: '#4ecdc4',
    glow: 'rgba(78, 205, 196, 0.5)',
    tag: 'KẾ HOẠCH',
    size: 96,
    transition: 'cloud',
    ambienceId: 'ambient_town_square',
    unlockLevel: 1,
    defaultLevel: 1
  },
  gym: {
    id: 'gym',
    name: 'Võ Đường Gym & Đẩy Tạ',
    subtitle: 'Rèn Luyện Thể Lực · Đồng Hồ Bấm Giờ',
    category: 'fitness',
    position: { x: 28, y: 38 },
    characterAnchor: { x: 28, y: 45 },
    img: './assets/buildings/gym.png',
    icon: '🏋️',
    color: '#ff6b6b',
    glow: 'rgba(255, 107, 107, 0.5)',
    tag: 'THỂ LỰC',
    size: 96,
    transition: 'cloud',
    ambienceId: 'ambient_gym_energy',
    unlockLevel: 1,
    defaultLevel: 1
  },
  water: {
    id: 'water',
    name: 'Đài Phun Nước Bù Nước',
    subtitle: 'Theo Dõi 2.500ml Nước & Điện Giải',
    category: 'wellness',
    position: { x: 48, y: 72 },
    characterAnchor: { x: 48, y: 78 },
    img: './assets/buildings/water.png',
    icon: '💧',
    color: '#45b7d1',
    glow: 'rgba(69, 183, 209, 0.5)',
    tag: 'DINH DƯỠNG',
    size: 92,
    transition: 'water',
    ambienceId: 'ambient_water_fountain',
    unlockLevel: 1,
    defaultLevel: 1
  },
  sleep: {
    id: 'sleep',
    name: 'Vườn Ngủ Say 90 Phút',
    subtitle: 'Chu Kỳ Giấc Ngủ · Âm Thanh Thư Giãn',
    category: 'wellness',
    position: { x: 78, y: 65 },
    characterAnchor: { x: 78, y: 72 },
    img: './assets/buildings/sleep.png',
    icon: '🌙',
    color: '#9b5de5',
    glow: 'rgba(155, 93, 229, 0.5)',
    tag: 'GIẤC NGỦ',
    size: 92,
    transition: 'moon',
    ambienceId: 'ambient_sleep_lullaby',
    unlockLevel: 1,
    defaultLevel: 1
  },
  journal: {
    id: 'journal',
    name: 'Thư Viện Nhật Ký Yêu Thương',
    subtitle: 'Nhật Ký Cảm Xúc & Kỷ Niệm',
    category: 'romance',
    position: { x: 18, y: 65 },
    characterAnchor: { x: 18, y: 72 },
    img: './assets/buildings/journal.png',
    icon: '📖',
    color: '#f15bb5',
    glow: 'rgba(241, 91, 181, 0.5)',
    tag: 'NHẬT KÝ',
    size: 92,
    transition: 'book',
    ambienceId: 'ambient_library_cozy',
    unlockLevel: 1,
    defaultLevel: 1
  },
  album: {
    id: 'album',
    name: 'Tiệm Ảnh Polaroid Kỷ Niệm',
    category: 'romance',
    subtitle: 'Kho Ảnh Hẹn Hò & Dấu Mốc Đôi Ta',
    position: { x: 32, y: 78 },
    characterAnchor: { x: 32, y: 84 },
    img: './assets/buildings/album.png',
    icon: '📸',
    color: '#fee440',
    glow: 'rgba(254, 228, 64, 0.5)',
    tag: 'ALBUM',
    size: 92,
    transition: 'camera',
    ambienceId: 'ambient_camera_click',
    unlockLevel: 1,
    defaultLevel: 1
  },
  market: {
    id: 'market',
    name: 'Chợ Phiên Dinh Dưỡng',
    subtitle: 'Thực Đơn Healthy · Ăn Sạch Bổ Dưỡng',
    category: 'dining',
    position: { x: 82, y: 42 },
    characterAnchor: { x: 82, y: 48 },
    img: './assets/buildings/market.png',
    icon: '🛒',
    color: '#00f5d4',
    glow: 'rgba(0, 245, 212, 0.5)',
    tag: 'CHỢ PHIÊN',
    size: 92,
    transition: 'cloud',
    ambienceId: 'ambient_market_bustle',
    unlockLevel: 1,
    defaultLevel: 1
  },
  restaurant: {
    id: 'restaurant',
    name: 'Nhà Hàng Bữa Tối Lãng Mạn',
    subtitle: 'Queen Ann Sky Lounge · Đặt Bàn Đôi',
    category: 'dining',
    position: { x: 62, y: 78 },
    characterAnchor: { x: 62, y: 84 },
    img: './assets/buildings/restaurant.png',
    icon: '🍽️',
    color: '#ff9e00',
    glow: 'rgba(255, 158, 0, 0.5)',
    tag: 'HẸN HÒ',
    size: 92,
    transition: 'heart',
    ambienceId: 'ambient_restaurant_jazz',
    unlockLevel: 1,
    defaultLevel: 1
  },
  airport: {
    id: 'airport',
    name: 'Sân Bay Chuyến Bay 27/08',
    subtitle: 'Vé Bay Đi Nha Trang & Quỹ MOMO 8Tr',
    category: 'adventure',
    position: { x: 88, y: 18 },
    characterAnchor: { x: 88, y: 25 },
    img: './assets/buildings/airport.png',
    icon: '✈️',
    color: '#00bbf9',
    glow: 'rgba(0, 187, 249, 0.5)',
    tag: 'CHUYẾN BAY',
    size: 96,
    transition: 'plane',
    ambienceId: 'ambient_airport_terminal',
    unlockLevel: 1,
    defaultLevel: 1
  },
  beach: {
    id: 'beach',
    name: 'Bãi Biển Tour 3 Đảo Nha Trang',
    subtitle: 'Mini Beach · Hòn Mun · Viện Hải Dương',
    category: 'adventure',
    position: { x: 12, y: 18 },
    characterAnchor: { x: 12, y: 25 },
    img: './assets/buildings/beach.png',
    icon: '🏖️',
    color: '#38b000',
    glow: 'rgba(56, 176, 0, 0.5)',
    tag: 'TOUR BIỂN',
    size: 96,
    transition: 'water',
    ambienceId: 'ambient_beach_waves',
    unlockLevel: 1,
    defaultLevel: 1
  },
  hospital: {
    id: 'hospital',
    name: 'Bệnh Viện Tình Yêu Flo Cycle',
    subtitle: 'Theo Dõi Chu Kỳ & Cẩm Nang Haru Chăm Sóc',
    category: 'wellness',
    position: { x: 35, y: 22 },
    characterAnchor: { x: 35, y: 28 },
    img: './assets/buildings/hospital.png',
    icon: '🏥',
    color: '#ff70a6',
    glow: 'rgba(255, 112, 166, 0.5)',
    tag: 'SỨC KHỎE',
    size: 96,
    transition: 'heart',
    ambienceId: 'ambient_hospital_calm',
    unlockLevel: 1,
    defaultLevel: 1
  },
  settings: {
    id: 'settings',
    name: 'Tòa Thị Chính Quản Trị',
    subtitle: 'Cài Đặt Hệ Thống & Khóa Mã PIN Bảo Mật',
    category: 'core',
    position: { x: 65, y: 22 },
    characterAnchor: { x: 65, y: 28 },
    img: './assets/buildings/settings.png',
    icon: '⚙️',
    color: '#70d6ff',
    glow: 'rgba(112, 214, 255, 0.5)',
    tag: 'QUẢN TRỊ',
    size: 96,
    transition: 'gear',
    ambienceId: 'ambient_townhall_clock',
    unlockLevel: 1,
    defaultLevel: 1
  }
}

export function getAllLocations(): WorldLocation[] {
  return Object.values(WORLD_LOCATIONS)
}

export function getLocationById(id: LocationId): WorldLocation {
  return (
    WORLD_LOCATIONS[id] || {
      id,
      name: `Công Trình ${id}`,
      subtitle: 'Khám phá khu vực',
      category: 'core',
      position: { x: 50, y: 50 },
      characterAnchor: { x: 50, y: 55 },
      img: './assets/buildings/home.png',
      icon: '📍',
      color: '#ff8da1',
      glow: 'rgba(255, 141, 161, 0.4)',
      tag: 'KHÁM PHÁ',
      size: 90,
      transition: 'cloud',
      ambienceId: 'ambient_default',
      unlockLevel: 1,
      defaultLevel: 1
    }
  )
}
